name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: Install deps
        run: yarn
      - name: Run lint and format
        run: yarn lint:fix
      - name: Run test
        run: yarn test
      - name: Run build
        run: yarn build
